CREATE TABLE permissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by_id BIGINT,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_by_id BIGINT,
    name          VARCHAR(255)                            NOT NULL,
    description   VARCHAR(255),
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE role_permissions
(
    permission_id BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE roles
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by_id BIGINT,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_by_id BIGINT,
    name          VARCHAR(255),
    description   VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id            BIGINT  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by_id BIGINT,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_by_id BIGINT,
    username      VARCHAR(255),
    password      VARCHAR(255),
    enabled       BOOLEAN NOT NULL,
    role_id       BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_permissions
(
    type          VARCHAR(255),
    user_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_user_permissions PRIMARY KEY (user_id, permission_id)
);

ALTER TABLE permissions
    ADD CONSTRAINT uc_permissions_name UNIQUE (name);

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_permission FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_role FOREIGN KEY (role_id) REFERENCES roles (id);